window.__SHARED_PICKS__ = {
  "updatedAt": "2026-09-04T18:03:38.875Z",
  "entries": [
    {
      "title": "25 Central Park West #19U",
      "address": "25 Central Park West #19U, NEW YORK, NY, 10023",
      "price": 6700,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 788,
      "neighborhood": "Lincoln Square",
      "availableDate": "2026-09-15",
      "kitchenLayout": "closed",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-century-condominium/19u",
      "note": "Nice but many illegal fees associated with application. Priced way over market. Edit: the extra fees may be condo board fess, possible legal.",
      "status": "gone"
    },
    {
      "title": "550 Vanderbilt Avenue #717",
      "address": "550 Vanderbilt Avenue #717, BROOKLYN, NY, 11238",
      "price": 4850,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 642,
      "neighborhood": "Prospect Heights",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/550-vanderbilt-avenue-brooklyn/717",
      "note": "Very promising. Close to matt and neela. For the price, hard to do better.",
      "status": "gone"
    },
    {
      "title": "214 Garfield Place #3",
      "address": "214 Garfield Place #3, BROOKLYN, NY, 11215",
      "price": 5250,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": "2026-07-19",
      "kitchenLayout": "open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/214-garfield-place-brooklyn/3",
      "note": "It's an open kitchen. Beautiful apartment.",
      "status": "gone"
    },
    {
      "title": "24-15 Queens Plaza North #6A",
      "address": "24-15 Queens Plaza North #6A, LONG ISLAND CITY, NY, 11101",
      "price": 6250,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": 1219,
      "neighborhood": "Long Island City",
      "availableDate": null,
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/view-59/6a",
      "note": "",
      "status": "gone"
    },
    {
      "title": "4610 Center Boulevard #517",
      "address": "4610 Center Boulevard #517, LONG ISLAND CITY, NY, 11109",
      "price": 5960,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Hunters Point",
      "availableDate": "2026-08-07",
      "kitchenLayout": "open",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/4610-center-blvd/517",
      "note": "Promising. Sort of a cramped layout.",
      "status": "gone"
    },
    {
      "title": "45 Garnet Street #1B",
      "address": "45 Garnet Street #1B, BROOKLYN, NY, 11231",
      "price": 4900,
      "bedrooms": 1,
      "bathrooms": 1.5,
      "sqft": 1288,
      "neighborhood": "Carroll Gardens",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/45-garnet-street-brooklyn/1b",
      "note": "Comes with accessory space, which is enticing. However, I think this unit is on the first floor, which could cause some issues. Also a bit close to the gowanus canal (poison)",
      "status": "qualifying"
    },
    {
      "title": "354 2nd Street #3A",
      "address": "354 2nd Street #3A, BROOKLYN, NY, 11215",
      "price": 4800,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": "2026-07-15",
      "kitchenLayout": "closed",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/354-2-street-brooklyn/3a",
      "note": "",
      "status": "gone"
    },
    {
      "title": "403 12th Street #4",
      "address": "403 12th Street #4, BROOKLYN, NY, 11215",
      "price": 5499,
      "bedrooms": 3,
      "bathrooms": 1,
      "sqft": 1200,
      "neighborhood": "Park Slope",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/390-7-avenue-brooklyn/4",
      "note": "Absolutely amazing. Huge kitchen. realtor is a scumbag.",
      "status": "gone"
    },
    {
      "title": "11-25 45th Avenue #3G",
      "address": "11-25 45th Avenue #3G, LONG ISLAND CITY, NY, 11101",
      "price": 4550,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 750,
      "neighborhood": "Hunters Point",
      "availableDate": "2026-08-04",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/one-murray-park/3g",
      "note": "Very nice. Big rooms.",
      "status": "gone"
    },
    {
      "title": "46 Putnam Avenue #3",
      "address": "46 Putnam Avenue #3, BROOKLYN, NY, 11238",
      "price": 6500,
      "bedrooms": 3,
      "bathrooms": 2,
      "sqft": 900,
      "neighborhood": "Clinton Hill",
      "availableDate": "2026-08-05",
      "kitchenLayout": "open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/46-putnam-avenue-brooklyn/3",
      "note": "Confirmed induction stove, but the kitchen is otherwise amazing. Huge table is a massive plus. I love this place.",
      "status": "gone"
    },
    {
      "title": "150 Clermont Avenue #5E",
      "address": "150 Clermont Avenue #5E, BROOKLYN, NY, 11205",
      "price": 5650,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Fort Greene",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-clermont-375-myrtle-avenue-brooklyn/5e",
      "note": "Actual kitchen looks to be quite large, but only visible in past listing photos. Commute is not great, but huge apartment for the price.",
      "status": "gone"
    },
    {
      "title": "589 5th Avenue #3R",
      "url": "https://streeteasy.com/building/589-5-avenue-brooklyn/3r",
      "note": "Price reduced to 6300",
      "status": "unknown"
    },
    {
      "title": "155 Luquer Street #2",
      "url": "https://streeteasy.com/building/155-luquer-street-brooklyn/2",
      "note": "",
      "status": "unknown"
    },
    {
      "title": "957 Atlantic Avenue #901",
      "url": "https://streeteasy.com/building/the-alanza/901",
      "note": "In contract 8/12/2026",
      "status": "gone"
    },
    {
      "title": "267 Pacific Street #403",
      "address": "267 Pacific Street #403, BROOKLYN, NY, 11201",
      "price": 5075,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Cobble Hill",
      "availableDate": "2026-09-04",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/267-pacific-street-brooklyn/403",
      "note": "Confirmed gas. Rented 8/23/2026",
      "status": "gone"
    },
    {
      "title": "610 Warren Street #6D",
      "url": "https://streeteasy.com/building/610-warren-street-brooklyn/6d",
      "note": "Nice gas stove. Seems like a very large living room.",
      "status": "unknown"
    },
    {
      "title": "375 Dean Street #603",
      "address": "375 Dean Street #603, BROOKLYN, NY, 11217",
      "price": 5799,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 951,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/signum-375-dean-street-brooklyn/603",
      "note": "",
      "status": "gone"
    },
    {
      "title": "26 Quincy Street #502",
      "address": "26 Quincy Street #502, BROOKLYN, NY, 11238",
      "price": 5400,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Clinton Hill",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/26-quincy-street-brooklyn/502",
      "note": "Weird. No real website. Possible new? Rented 8/17/2026",
      "status": "gone"
    },
    {
      "title": "656 Dean Street #2",
      "address": "656 Dean Street #2, BROOKLYN, NY, 11238",
      "price": 4750,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Prospect Heights",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/656-dean-street-brooklyn/2",
      "note": "Gas stove, actually. Not bad! Kitchen looks outdated, but it's fine.",
      "status": "gone"
    },
    {
      "title": "556 Baltic Street #503",
      "address": "556 Baltic Street #503, NEW YORK, NY, 11217",
      "price": 5300,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Boerum Hill",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/baltic-house-556-baltic-street/503",
      "note": "",
      "status": "gone"
    },
    {
      "title": "122 Willoughby Avenue #2",
      "address": "122 Willoughby Avenue #2, BROOKLYN, NY, 11205",
      "price": 5900,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Clinton Hill",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/122-willoughby-avenue-brooklyn/2",
      "note": "Electric, not gas. Beautiful though.",
      "status": "gone"
    },
    {
      "title": "131 Fifth Avenue #3B",
      "address": "131 Fifth Avenue #3B, BROOKLYN, NY, 11217",
      "price": 4200,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/131-5-avenue-brooklyn/3b",
      "note": "",
      "status": "gone"
    },
    {
      "title": "470 Dean Street #4104",
      "address": "470 Dean Street #4104, BROOKLYN, NY, 11217",
      "price": 4750,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 727,
      "neighborhood": "Prospect Heights",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-heritage-dean-street/4104",
      "note": "one bedroom a bit of a bummer but overall pretty sick. Gas stove a huge plus.",
      "status": "gone"
    },
    {
      "title": "100 Steuben Street #5A",
      "url": "https://streeteasy.com/building/100-steuben-street-brooklyn/5a",
      "note": "Gas, rent stabilized. Very nice. Street kinda sucks (lotta auto body shops. Delisted 8/12/2026",
      "status": "gone"
    },
    {
      "title": "286 5th Avenue #4D",
      "address": "286 5th Avenue #4D, BROOKLYN, NY, 11215",
      "price": 4200,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/286-5-avenue-brooklyn/4d",
      "note": "Gas stove. Tight kitchen though.",
      "status": "qualifying"
    },
    {
      "title": "736 Washington Avenue #5F",
      "address": "736 Washington Avenue #5F, BROOKLYN, NY, 11238",
      "price": 4800,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Prospect Heights",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/736-washington-avenue-brooklyn/5f",
      "note": "Stove is gas. Weird layout though.",
      "status": "gone"
    },
    {
      "title": "433 Sackett Street #2H",
      "address": "433 Sackett Street #2H, BROOKLYN, NY, 11217",
      "price": 6100,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Carroll Gardens",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/433-sackett/2h",
      "note": "Eh. Very cool building though -- it's a renovated church. Rented 8/18/2026",
      "status": "gone"
    },
    {
      "title": "313 West 82nd Street #4B",
      "address": "313 West 82nd Street #4B, NEW YORK, NY, 10024",
      "price": 4800,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Upper West Side",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/313-west-82-street-new_york/4b",
      "note": "",
      "status": "gone"
    },
    {
      "title": "445 Grand Avenue #201",
      "url": "https://streeteasy.com/building/arris-grand/201",
      "note": "I don't know man. Building gets terrible reviews, but how bad could it possibly be? Units look great. Gas stoves, good location.",
      "status": "unknown"
    },
    {
      "title": "326 Bond Street #4F",
      "address": "326 Bond Street #4F, BROOKLYN, NY, 11231",
      "price": 6600,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Carroll Gardens",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/326-bond-street-brooklyn/4f",
      "note": "Weird but also cool",
      "status": "gone"
    },
    {
      "title": "97 Grand Avenue #1A",
      "url": "https://streeteasy.com/building/97-grand-avenue-brooklyn/1a",
      "note": "Really cool. Gas stove and outdoor area.",
      "status": "unknown"
    },
    {
      "title": "150 Clermont Avenue #4C",
      "address": "150 Clermont Avenue #4C, BROOKLYN, NY, 11205",
      "price": 5500,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Fort Greene",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/the-clermont-375-myrtle-avenue-brooklyn/4c",
      "note": "",
      "status": "gone"
    },
    {
      "title": "433 Sackett Street #2I",
      "url": "https://streeteasy.com/building/433-sackett/2i",
      "note": "",
      "status": "unknown"
    },
    {
      "title": "433 Sackett Street #4B",
      "url": "https://streeteasy.com/building/433-sackett/4b",
      "note": "Unclear if kitchen is closed",
      "status": "unknown"
    },
    {
      "title": "45 North Oxford Street #3",
      "address": "45 North Oxford Street #3, BROOKLYN, NY, 11205",
      "price": 4250,
      "bedrooms": 3,
      "bathrooms": 2,
      "sqft": 1325,
      "neighborhood": "Fort Greene",
      "availableDate": "2026-09-06",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/45-north-oxford-street-brooklyn/3",
      "note": "",
      "status": "gone"
    },
    {
      "title": "87 Irving Place, 3C",
      "address": "87 Irving Place, 3C, Brooklyn, NY, 11238",
      "price": 4250,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Clinton Hill",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "unknown",
      "url": "https://www.corcoran.com/listing/for-rent/87-irving-place-3c-brooklyn-ny-11238/23930120/regionId/1",
      "note": "Not sure if stove is electric or induction. Beautiful overall though.",
      "status": "gone"
    },
    {
      "title": "163 Washington Avenue #15B",
      "address": "163 Washington Avenue #15B, Brooklyn, NY, 11205",
      "price": 4395,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Clinton Hill",
      "availableDate": null,
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://www.openigloo.com/unit/nyc/3054410-3018907501-15b/brooklyn-clinton-hill-163-washington-avenue-11205-15b",
      "note": "",
      "status": "gone"
    },
    {
      "title": "75 Greene Avenue, 2D",
      "address": "75 Greene Avenue, 2D, Brooklyn, NY, 11238",
      "price": 5500,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Fort Greene",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "unknown",
      "url": "https://www.corcoran.com/listing/for-rent/75-greene-avenue-2d-brooklyn-ny-11238/23919656/regionId/1",
      "note": "great location, super pretty. Gas stove. Expensive for what it is but also...it's so nice. Fully furnished(?)",
      "status": "gone"
    },
    {
      "title": "74 Vanderbilt Avenue",
      "address": "74 Vanderbilt Avenue, Fort Greene, NY, 11205",
      "price": 5600,
      "bedrooms": 1,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Fort Greene",
      "availableDate": null,
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://www.compass.com/homedetails/74-Vanderbilt-Ave-Brooklyn-NY-11205/20ZOXE_pid/",
      "note": "oh my god. It's amazing. Terrible accessibility though.",
      "status": "qualifying"
    },
    {
      "title": "267 6th Street, Unit 6K",
      "address": "267 6th Street, Unit 6K, Park Slope, NY, 11215",
      "price": 6000,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": null,
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://www.compass.com/homedetails/267-6th-St-Unit-6K-Brooklyn-NY-11215/213P13_pid/",
      "note": "too expensive. Listed at 6k elsewhere so what's the real price?",
      "status": "gone"
    },
    {
      "title": "150 Myrtle Avenue #1907",
      "address": "150 Myrtle Avenue #1907, BROOKLYN, NY, 11201",
      "price": 4000,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Downtown Brooklyn",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/toren-condominium/1907",
      "note": "",
      "status": "gone"
    },
    {
      "title": "150 Clermont Avenue #4E",
      "address": "150 Clermont Avenue #4E, BROOKLYN, NY, 11205",
      "price": 5650,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Fort Greene",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-clermont-375-myrtle-avenue-brooklyn/4e",
      "note": "Big contender. Margo was very responsive. Tour if still available. Update: margo a bit weird, unit is great, location not great, building has complaints",
      "status": "qualifying"
    },
    {
      "title": "60 Riverside Boulevard #1908",
      "address": "60 Riverside Boulevard #1908, NEW YORK, NY, 10069",
      "price": 6300,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 839,
      "neighborhood": "Lincoln Square",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-aldyn/1908",
      "note": "too expensive",
      "status": "gone"
    },
    {
      "title": "81 Fleet Place #12L",
      "address": "81 Fleet Place #12L, BROOKLYN, NY, 11201",
      "price": 4847,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 641,
      "neighborhood": "Downtown Brooklyn",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/the-giovanni/12l",
      "note": "",
      "status": "qualifying"
    },
    {
      "title": "375 Dean Street #443",
      "address": "375 Dean Street #443, BROOKLYN, NY, 11217",
      "price": 5699,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 951,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/signum-375-dean-street-brooklyn/443",
      "note": "",
      "status": "gone"
    },
    {
      "title": "150 Myrtle Avenue #309",
      "address": "150 Myrtle Avenue #309, BROOKLYN, NY, 11201",
      "price": 6499,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": 1046,
      "neighborhood": "Downtown Brooklyn",
      "availableDate": "2026-09-14",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/toren-condominium/309",
      "note": "Moderate income restriction, so I don't think I'm eligible",
      "status": "qualifying"
    },
    {
      "title": "169 15th Street #3A",
      "address": "169 15th Street #3A, BROOKLYN, NY, 11215",
      "price": 4400,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": "2026-10-01",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/169-15-street-brooklyn/3a",
      "note": "Kitchen is a wild card. Could be small. What a great price though. Maybe I could expand the kitchen. Consider for a tour.",
      "status": "qualifying"
    },
    {
      "title": "10 Nevins Street #9A",
      "address": "10 Nevins Street #9A, BROOKLYN, NY, 11217",
      "price": 6400,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": 984,
      "neighborhood": "Downtown Brooklyn",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/the-brooklyn-grove/9a",
      "note": "",
      "status": "gone"
    },
    {
      "title": "1118 Fulton Street #5F",
      "address": "1118 Fulton Street #5F, BROOKLYN, NY, 11238",
      "price": 4250,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 618,
      "neighborhood": "Bedford-Stuyvesant",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/1118-fulton-street-brooklyn/5f",
      "note": "Gas stove. Hard to say. A bit small.",
      "status": "qualifying"
    },
    {
      "title": "375 Dean Street #311",
      "address": "375 Dean Street #311, BROOKLYN, NY, 11217",
      "price": 4199,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 601,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/signum-375-dean-street-brooklyn/311",
      "note": "",
      "status": "gone"
    },
    {
      "title": "155 Luquer Street, Unit 2",
      "address": "155 Luquer Street, Unit 2, Carroll Gardens, NY, 11231",
      "price": 6425,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Carroll Gardens",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "smoothElectric",
      "url": "https://www.compass.com/homedetails/155-Luquer-St-Unit-2-Brooklyn-NY-11231/202W1S_pid/",
      "note": "Out of budget but pretty sick. Could be worth it.",
      "status": "qualifying"
    },
    {
      "title": "605 Vanderbilt Avenue, Unit 2",
      "address": "605 Vanderbilt Avenue, Unit 2, Prospect Heights, NY, 11238",
      "price": 4750,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Prospect Heights",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://www.compass.com/homedetails/605-Vanderbilt-Ave-Unit-2-Brooklyn-NY-11238/20UUDV_pid/",
      "note": "Not really a 2bed. But close. Otherwise great. Worth touring if it's available.",
      "status": "qualifying"
    },
    {
      "title": "656 Dean Street, Unit 2",
      "address": "656 Dean Street, Unit 2, Prospect Heights, NY, 11238",
      "price": 4750,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Prospect Heights",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://www.compass.com/homedetails/656-Dean-St-Unit-2-Brooklyn-NY-11238/20L9CH_pid/",
      "note": "",
      "status": "gone"
    },
    {
      "title": "375 Dean Street #1316",
      "address": "375 Dean Street #1316, BROOKLYN, NY, 11217",
      "price": 5999,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": 751,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/signum-375-dean-street-brooklyn/1316",
      "note": "I think this might actually be fine. It's a walk-through kitchen.",
      "status": "gone"
    },
    {
      "title": "545 Vanderbilt Avenue #10G",
      "address": "545 Vanderbilt Avenue #10G, Brooklyn, NY, 11238",
      "price": 3950,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Clinton Hill",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "unknown",
      "url": "https://www.openigloo.com/unit/nyc/3057522-3020107505-10g/brooklyn-clinton-hill-545-vanderbilt-avenue-11238-10g",
      "note": "",
      "status": "gone"
    },
    {
      "title": "163 Washington Avenue #15B",
      "address": "163 Washington Avenue #15B, BROOKLYN, NY, 11205",
      "price": 4295,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 701,
      "neighborhood": "Clinton Hill",
      "availableDate": "now",
      "kitchenLayout": "unknown",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/163-washington-avenue-brooklyn/15b",
      "note": "Kitchen is open according to floorplan and video.",
      "status": "excluded",
      "reasons": [
        "Kitchen layout could not be confirmed from photos"
      ]
    },
    {
      "title": "306 Saint James Place #4F",
      "address": "306 Saint James Place #4F, BROOKLYN, NY, 11238",
      "price": 4245,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Clinton Hill",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/306-st-james-place-brooklyn/4f",
      "note": "",
      "status": "gone"
    },
    {
      "title": "275 Park Avenue #5F",
      "address": "275 Park Avenue #5F, BROOKLYN, NY, 11205",
      "price": 6150,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": 1080,
      "neighborhood": "Clinton Hill",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/275-park-avenue-brooklyn/5f",
      "note": "Gas stove. Famous building. Not very accessible.",
      "status": "excluded",
      "reasons": [
        "Kitchen photo shows a closed layout"
      ]
    },
    {
      "title": "433 Sackett Street #4G",
      "address": "433 Sackett Street #4G, BROOKLYN, NY, 11217",
      "price": 6000,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Carroll Gardens",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/433-sackett/4g",
      "note": "cannot tell if closed.",
      "status": "gone"
    },
    {
      "title": "433 Sackett Street #4C",
      "address": "433 Sackett Street #4C, BROOKLYN, NY, 11217",
      "price": 6300,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Carroll Gardens",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/433-sackett/4c",
      "note": "",
      "status": "gone"
    },
    {
      "title": "433 Sackett Street #4D",
      "address": "433 Sackett Street #4D, BROOKLYN, NY, 11217",
      "price": 6300,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Carroll Gardens",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/433-sackett/4d",
      "note": "",
      "status": "gone"
    },
    {
      "title": "433 Sackett Street #4F",
      "address": "433 Sackett Street #4F, BROOKLYN, NY, 11217",
      "price": 6300,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Carroll Gardens",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/433-sackett/4f",
      "note": "",
      "status": "gone"
    },
    {
      "title": "162 16th Street #10A",
      "address": "162 16th Street #10A, BROOKLYN, NY, 11215",
      "price": 6999,
      "bedrooms": 3,
      "bathrooms": 2,
      "sqft": 1168,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/vue-condominium/10a",
      "note": "A bit over budget but super super nice. Gas stove and open enough kitchen.",
      "status": "excluded",
      "reasons": [
        "Kitchen photo shows a closed layout"
      ]
    },
    {
      "title": "131 Smith Street #3L",
      "address": "131 Smith Street #3L, BROOKLYN, NY, 11201",
      "price": 5325,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Boerum Hill",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/131-smith-street-brooklyn/3l",
      "note": "Unclear layout. Very cool. Good location. hard to tell if stove electric or induction.",
      "status": "gone"
    },
    {
      "title": "275 Park Avenue #3I",
      "address": "275 Park Avenue #3I, BROOKLYN, NY, 11205",
      "price": 4295,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 670,
      "neighborhood": "Clinton Hill",
      "availableDate": "now",
      "kitchenLayout": "closed",
      "stoveType": "coilElectric",
      "url": "https://streeteasy.com/building/275-park-avenue-brooklyn/3i",
      "note": "unclear about stove or kitchen.",
      "status": "excluded",
      "reasons": [
        "Kitchen photo shows a closed layout",
        "Coil electric stove (explicitly rejected)"
      ]
    },
    {
      "title": "163 Washington Avenue #12C",
      "address": "163 Washington Avenue #12C, BROOKLYN, NY, 11205",
      "price": 5325,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": 982,
      "neighborhood": "Clinton Hill",
      "availableDate": "now",
      "kitchenLayout": "unknown",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/163-washington-avenue-brooklyn/12c",
      "note": "open layout but no photos of the actual unit. There's a video now which is promising.",
      "status": "excluded",
      "reasons": [
        "Kitchen layout could not be confirmed from photos"
      ]
    },
    {
      "title": "387 7th Avenue #2",
      "address": "387 7th Avenue #2, BROOKLYN, NY, 11215",
      "price": 6000,
      "bedrooms": 3,
      "bathrooms": 2,
      "sqft": 950,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/387-7-avenue-brooklyn/2",
      "note": "This is a top priority unit.",
      "status": "qualifying"
    },
    {
      "title": "60 Riverside Boulevard #725",
      "address": "60 Riverside Boulevard #725, NEW YORK, NY, 10069",
      "price": 6623,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 808,
      "neighborhood": "Lincoln Square",
      "availableDate": "2026-09-16",
      "kitchenLayout": "closed",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-aldyn/725",
      "note": "way out of budget",
      "status": "excluded",
      "reasons": [
        "Kitchen photo shows a closed layout"
      ]
    },
    {
      "title": "475 Clermont Avenue #714",
      "address": "475 Clermont Avenue #714, BROOKLYN, NY, 11238",
      "price": 5282,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 595,
      "neighborhood": "Fort Greene",
      "availableDate": "2026-09-04",
      "kitchenLayout": "closed",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/475-clermont/0714",
      "note": "expensive for a 1 bed but not bad overall. Gas stove.",
      "status": "excluded",
      "reasons": [
        "Kitchen photo shows a closed layout"
      ]
    },
    {
      "title": "376 Baltic Street #1BB",
      "address": "376 Baltic Street #1BB, BROOKLYN, NY, 11201",
      "price": 5750,
      "bedrooms": 1,
      "bathrooms": 1.5,
      "sqft": 1263,
      "neighborhood": "Boerum Hill",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/376-baltic-street-brooklyn/1bb",
      "note": "What a bizarre apartment. Cool though.",
      "status": "gone"
    },
    {
      "title": "375 Dean Street #453",
      "address": "375 Dean Street #453, BROOKLYN, NY, 11217",
      "price": 5699,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 1001,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/signum-375-dean-street-brooklyn/453",
      "note": "Rennit apparently a bit sketchy.",
      "status": "qualifying"
    },
    {
      "title": "161 West 61st Street #4H",
      "address": "161 West 61st Street #4H, NEW YORK, NY, 10023",
      "price": 5800,
      "bedrooms": 1,
      "bathrooms": 1.5,
      "sqft": 740,
      "neighborhood": "Lincoln Square",
      "availableDate": "2026-09-15",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-alfred/4h",
      "note": "Honestly pretty cool. I could walk to work some days.",
      "status": "gone"
    },
    {
      "title": "490 Myrtle Avenue #3A",
      "address": "490 Myrtle Avenue #3A, BROOKLYN, NY, 11205",
      "price": 5600,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Clinton Hill",
      "availableDate": "2026-09-11",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-refinery/3a",
      "note": "Living room and kitchen might be a little cramped but has a gas stove and two beds as well as an office. I would say this is quite promising",
      "status": "qualifying"
    },
    {
      "title": "168 East 66th Street #3",
      "address": "168 East 66th Street #3, NEW YORK, NY, 10065",
      "price": 5900,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Lenox Hill",
      "availableDate": "2026-10-01",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/1128-3-avenue-new_york/3",
      "note": "Honestly pretty sick. Temporarily off market 9/3",
      "status": "gone"
    },
    {
      "title": "180 Franklin Avenue #119",
      "address": "180 Franklin Avenue #119, BROOKLYN, NY, 11205",
      "price": 5438,
      "bedrooms": 2,
      "bathrooms": 2.5,
      "sqft": 1311,
      "neighborhood": "Bedford-Stuyvesant",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/180-franklin-avenue-brooklyn/119",
      "note": "oh HELL yeah. I should definitely tour it if it's available. Not very accessible.",
      "status": "qualifying"
    },
    {
      "title": "267 6th Street, Unit 6K Park Slope",
      "address": "267 6th Street, Unit 6K, Park Slope, NY, 11215",
      "price": 6000,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": null,
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://www.compass.com/homedetails/267-6th-St-Unit-6K-Brooklyn-NY-11215/2166223652155352537_lid/",
      "note": "Pretty sure the building is kinda cheeks but whatever.",
      "status": "gone"
    },
    {
      "title": "531 Myrtle Avenue #5F",
      "address": "531 Myrtle Avenue #5F, BROOKLYN, NY, 11205",
      "price": 4960,
      "bedrooms": 2,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Clinton Hill",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/529-myrtle-avenue-brooklyn/5f",
      "note": "gas stove. Rent stablized. Consider strongly.",
      "status": "qualifying"
    },
    {
      "title": "540 Fulton Street #20G",
      "address": "540 Fulton Street #20G, BROOKLYN, NY, 11201",
      "price": 6213,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": 911,
      "neighborhood": "Downtown Brooklyn",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-paxton-540-fulton-street-brooklyn/20g",
      "note": "Technically downtown brooklyn but really at the intersection of fort greene and boerum hill. Gas stove. Worth a shot maybe. Management seems fine. Area is a bit busy.",
      "status": "gone"
    },
    {
      "title": "196 Willoughby Street #17M",
      "address": "196 Willoughby Street #17M, Brooklyn, NY, 11201",
      "price": 4536,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Fort Greene",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "unknown",
      "url": "https://www.openigloo.com/unit/nyc/3426373-3020857502-17m/brooklyn-fort-greene-196-willoughby-street-11201-17m",
      "note": "",
      "status": "qualifying"
    },
    {
      "title": "316 Bergen St #4-05",
      "address": "316 Bergen St #4-05, Brooklyn, NY, 11217",
      "price": 4649,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Boerum Hill",
      "availableDate": null,
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://www.openigloo.com/unit/nyc/3397486-3003890005-4-05/brooklyn-boerum-hill-316-bergen-st-11217-4-05",
      "note": "The Bergen is pretty well rated.",
      "status": "qualifying"
    },
    {
      "title": "316 Bergen Street #7-7",
      "address": "316 Bergen Street #7-7, BROOKLYN, NY, 11217",
      "price": 5995,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": 939,
      "neighborhood": "Boerum Hill",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/the-bergen/707",
      "note": "Strongly consider units at the bergen. Great location and management. Gas stoves. 707 is galley kitchen and huge terrace though. Sad.",
      "status": "qualifying"
    },
    {
      "title": "196 7th Avenue #8",
      "address": "196 7th Avenue #8, BROOKLYN, NY, 11215",
      "price": 5900,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/196-7-avenue-brooklyn/8",
      "note": "Hard to say what's going on here. Could be good?",
      "status": "qualifying"
    },
    {
      "title": "316 Bergen Street #4-5",
      "address": "316 Bergen Street #4-5, BROOKLYN, NY, 11217",
      "price": 4649,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 625,
      "neighborhood": "Boerum Hill",
      "availableDate": "2026-10-05",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/the-bergen/405",
      "note": "The bergen is a good building. Consider.",
      "status": "qualifying"
    },
    {
      "title": "55 Paseo Place, Unit 322",
      "address": "55 Paseo Place, Unit 322, Park Slope, NY, 11217",
      "price": 5150,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Park Slope",
      "availableDate": null,
      "kitchenLayout": "semi-open",
      "stoveType": "unknown",
      "url": "https://www.compass.com/homedetails/55-Paseo-Pl-Unit-322-Brooklyn-NY-11217/267MOP_pid/",
      "note": "",
      "status": "qualifying"
    },
    {
      "title": "316 Bergen Street #70-3",
      "address": "316 Bergen Street #70-3, BROOKLYN, NY, 11217",
      "price": 6195,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": 852,
      "neighborhood": "Boerum Hill",
      "availableDate": "2026-09-09",
      "kitchenLayout": "open",
      "stoveType": "smoothElectric",
      "url": "https://streeteasy.com/building/the-bergen/703",
      "note": "They've reduced price to 6195. Great building with excellent accessibility. I think this building is a priority.",
      "status": "qualifying"
    },
    {
      "title": "595 Dean Street #1032",
      "address": "595 Dean Street #1032, BROOKLYN, NY, 11238",
      "price": 4635,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": null,
      "neighborhood": "Prospect Heights",
      "availableDate": "now",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/595-dean-street-brooklyn/1032",
      "note": "As a last resort why not",
      "status": "qualifying"
    },
    {
      "title": "110 4th Avenue #3H",
      "address": "110 4th Avenue #3H, BROOKLYN, NY, 11217",
      "price": 5400,
      "bedrooms": 2,
      "bathrooms": 1.5,
      "sqft": null,
      "neighborhood": "Boerum Hill",
      "availableDate": "now",
      "kitchenLayout": "semi-open",
      "stoveType": "unknown",
      "url": "https://streeteasy.com/building/110-4-avenue-brooklyn/3h",
      "note": "Seems pretty good. I think strongly consider touring.",
      "status": "qualifying"
    },
    {
      "title": "475 Clermont Avenue #538",
      "address": "475 Clermont Avenue #538, BROOKLYN, NY, 11238",
      "price": 4607,
      "bedrooms": 1,
      "bathrooms": 1,
      "sqft": 546,
      "neighborhood": "Fort Greene",
      "availableDate": "2026-10-19",
      "kitchenLayout": "open",
      "stoveType": "gas",
      "url": "https://streeteasy.com/building/475-clermont/538",
      "note": "not this unit, but this building should be strongly considered",
      "status": "qualifying"
    },
    {
      "title": "316 Bergen St #7-07",
      "address": "316 Bergen St #7-07, Brooklyn, NY, 11217",
      "price": 5995,
      "bedrooms": 2,
      "bathrooms": 2,
      "sqft": null,
      "neighborhood": "Boerum Hill",
      "availableDate": null,
      "kitchenLayout": "open",
      "stoveType": "smoothElectric",
      "url": "https://www.openigloo.com/unit/nyc/3397486-3003890005-7-07/brooklyn-boerum-hill-316-bergen-st-11217-7-07",
      "note": "Very good building. Gas stove, 2 beds. High priority unit.",
      "status": "qualifying"
    }
  ]
};
